spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_project
    username: root
    password: 8619
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
